/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labirynt;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author adas
 */
public class VSearchSpeed extends javax.swing.JFrame {

    Labirynt labirynt;
    int speed = 0;
    /**
     * Creates new form VSearchSpeed
     * @param labirynt
     */
    public VSearchSpeed(Labirynt labirynt) {
        
        this.labirynt = labirynt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                disposeSearch(evt);
            }
        });

        jLabel1.setText("Prędkość: " + speed);

        jButton1.setText("+ 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseBy1(evt);
            }
        });

        jButton2.setText("+ 5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseBy5(evt);
            }
        });

        jButton3.setText("- 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseBy1(evt);
            }
        });

        jButton4.setText("- 5");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseBy5(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void increaseBy1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseBy1
        speed += 1;
        if(labirynt.onClickChangeSpeed(1)){
            jLabel1.setText("Prędkość : " + speed);
        }else{
            speed -= 1;
        }
    }//GEN-LAST:event_increaseBy1

    private void increaseBy5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseBy5
        speed += 5;
        if(labirynt.onClickChangeSpeed(5)){
            jLabel1.setText("Prędkość : " + speed);
        }else{
            speed -= 5;
        }
    }//GEN-LAST:event_increaseBy5

    private void decreaseBy1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseBy1
        if(speed > 0){
            speed -= 1;
            if(labirynt.onClickChangeSpeed(-1)){
                jLabel1.setText("Prędkość : " + speed);
            }else{
                speed += 1;
            }
        }
    }//GEN-LAST:event_decreaseBy1

    private void decreaseBy5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseBy5
        if(speed <= 4){
            speed = 0;
        }else{
            speed -= 5;
        }
        
        if(labirynt.onClickChangeSpeed(-5)){
            jLabel1.setText("Prędkość : " + speed);
        }else{
            speed += 5;
        }
    }//GEN-LAST:event_decreaseBy5

    private void disposeSearch(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_disposeSearch
        labirynt.onClickStopSearching();
    }//GEN-LAST:event_disposeSearch

    public void showSearchSpeed() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VSearchSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VSearchSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VSearchSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VSearchSpeed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        this.setVisible(true);
    }
    
    public void close(){
        this.setVisible(false);
        dispose();
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
